### ISSUE TITLE
Error in makefile

### ISSUE THREAD

**Issue by kyczawon** [m8pple/arch2-2018-cw#13]
If the command "make simulator" is called the following error is shown:
![screen shot 2017-11-14 at 3 50 57 pm](https://user-images.githubusercontent.com/20750370/32789458-c99c5c96-c953-11e7-949c-e301214688c6.jpg)

To fix it, the directory had to be specified in the bin/mips_simulator target:
"mkdir -p" had to be changed to "mkdir -p /bin"

**Comment by m8pple** [comment]
Yes, your're right, looks like a benign error from when I copied and pasted it in from a different repo.

Using `mkdir -p /bin` will remove the error, because `/bin` already exists in the file system as
an absolute path. However, the intent was to create a local directory, so the correction would
be `mkdir -p bin`.

Another way of dealing with this is simply to commit a file that lives in the `bin`
directory, then git will ensure that it exists when the repository is cloned. You
don't want to check-in binaries, so a common solution is to include a [`.gitignore`](https://help.github.com/articles/ignoring-files/) file in the `bin` directory.

This can contain the text:
```
# Ignore (don't add) everything...
*
# ... except for this .gitignore file
!.gitignore
```
