### ISSUE TITLE
Input and Output of the simulator

### ISSUE THREAD

**Issue by VasiliosRallis** [m8pple/arch2-2018-cw#14]
1. Can std::getchar and std::putchar only get called by lw and sw instructions when they are reading/writing to the  specified address or should all memory access instructions call these functions if they are reading/writing to the specified addresses (i.e. the lwl instruction)

2. In the specification, it is mentioned that we should "Return the 8-bit extended to 32-bits as the result of the memory read." Should this extension be signed or unsigned?

**Comment by kyczawon** [comment]
3. Would SW to memory location 0x30000004 output 4 separate bytes, just the least significant byte (as implied by the name putc), the whole word or would only SB be allowed to write to memory locations 0x30000004-0x30000007?

**Comment by m8pple** [comment]
Those are good questions:

1:

Given these two memory instructions represent IO devices, thinking about it from a hardware
point of view helps a bit. If someone is interacting with a raw device then they _really_ should
now what they are doing, and performing an unaligned read from a device that is explicitly
32-bits feels wrong - why would they be doing that?

Or looked at in another way, if they are performing LWL then we have two possibilities: the
read is aligned, or it is unaligned:

- Unaligned : at least one byte of the LWL (or LWR) lies outside the getc address, which is illegal,
  and so should result in some sort of address exception.

- Aligned: the LWL (or LWR) covers exactly the 32-bits, so would proceed as a normal
   aligned read. This forms a really obscure though technically correct case.

But in almost every normal piece of code you would never just see LWL, you would see a pair
of LWL and LWR. So then you would face the problem that one unaligned read actually pulled
two characters, one of which was discarded.

So my intepretation is:
- A LWL or LWR to the getc address is legal _only_ if the address is aligned
- In other cases it should result in an exception.

This backed up by a hardware interpretation: the "memory" sees LWL/LWR/LW as exactly the
same - someone is requesting a 32-bit aligned value from memory.

Though I would consider any counter-arguments to that interpretation.

**Comment by m8pple** [comment]
2 
> In the specification, it is mentioned that we should "Return the 8-bit extended to 32-bits as
> the result of the memory read." Should this extension be signed or unsigned?

This requires a detailed reading of the semantics of `getc`, and the difference between a `char` and
an `int`, and `EOF` versus the character `0xff`.

So two things that `getc` must enforce are that:
- Any valid `char` can be returned.
- It is possible to distinguish `EOF` (i.e. no more characters) from any valid `char`.

As this is hardware, I've explicitly defined `EOF` to be `-1`, and we have explicitly
defined it to be a 32-bit location. _Implicitly_ we also know that a `char` is 8-bits
because we are on MIPS (remember that this may not be true on obscure platforms).

So the equivalent read needs to distinguish any 8-bit character from the 32-bit
value `-1`. This leads us to the conclusion that the character must be zero-extended
up to 32-bits, while the value `-1` should be the full 32-bit `-1`.

So full C client code might look something like this
(the [`volatile`](https://en.wikipedia.org/wiki/Volatile_(computer_programming))
keyword indicates to the compiler that the value may return different values
for each read, even if it has been written to) :
```
volatile int32_t *GETC=(volatile int32_t *)0x30000000;

int32_t c=*GETC;
if( c == -1){
   // We have EOF
}else{
    uint8_t ch=(uint8_t)c;
    // Now work with the actual value
}
```

See for example [this discussion](https://stackoverflow.com/questions/11057259/fgetc-checking-eof).

**Comment by m8pple** [comment]
> Would SW to memory location 0x30000004 output 4 separate bytes, just the least significant byte
> (as implied by the name putc), the whole word or would only SB be allowed to write to memory
> locations 0x30000004-0x30000007?

Using similar logic to the above, I would argue that the only logical behaviour is for it to
choose your first suggestion: only output the least significant byte. But then we still
need to resolve whether SB or/and SW is allowed to write that address.

From the hardware IO devices point of view (e.g. a memory mapped [UART](https://en.wikipedia.org/wiki/Universal_asynchronous_receiver-transmitter))
SWL, SWR, SW, SH, and SL all look exactly the same. They are given an
aligned address that is being written, and 32-bit value to write. In order to
distinguish _which_ bytes should be written, then a byte enable signals
are used. This was discussed in one of the lectures in the context of SB;
it was the 4-bit mask which is used to decide which of the bytes in memory
is actually updated.

So byte enables might allow our UART to decide _which_ bytes are being
written, but then it would have to decide what order they are being written
in. Should the character at 0x30000004 be written before the character
at 0x30000005? This isn't specified, so it would be be the flip of coin which
way round people on either side interpreted it.

We can resolve all this from both sides by taking the simplest approach:
- Only the least significant byte is written
- Software can write to the address as SW (because the address range is
   explicitly 4), SH, or SB, but the address written must always be 0x30000004.

In hardware this would require no extra effort (it only needs to look at
the byte enable for the least significant byte), and provides a bit more
flexibility to the software side.

**Comment by VasiliosRallis** [comment]
If "Only the least significant byte is written" then should SH have to write to 0x30000006 and SB to address 0x30000007?

**Comment by m8pple** [comment]
Awesome :) - yes, i think you've identified some lazy thinking at the end there. 

I'll avoid rushing to say that's correct, as rushing the last response probably led to the error, but i strongly suspect you're right.

**Comment by patrickjohncyh** [comment]
When you say that "only the least significant byte is written", do you mean that only the least significant byte of the value in the register that you are trying to write to output is written? If that is so, I do not quite understand what VasiliosRallis is talking about.

**Comment by wmvndrscht** [comment]
@m8pple 
Sorry but I still don't quite understand getc for loading > 1 byte. 

Say for we have lw for getc at 0x300...0:
1. do we print out the four bytes (char) as one 32 bit?
2. Print out each byte (char) as zero extended 32 bit in order from ..0 -> ..3, then print out EOF.
also say we only have byte 0x3..0 written, the rest are 0's in ADDR_GETC, do we treat 0x3..1,2,3 etc as EOF?

Also this part "Block until a character is available (e.g. if a key needs to be pressed)"
Is this in the sense character in memory is not ready as this seems weird, or is that you just want the program to stop and then we press a random key to start the getc function?

Thanks

**Comment by m8pple** [comment]
I missed this when it was posted - I think I answered this verbally already, but
just for completeness:

The memory location is intended to model one end of a UART, using the semantics and
API of `putchar` and `getchar`. So [`getchar`](http://www.cplusplus.com/reference/cstdio/getchar/)
as a function returns an `int`, which is a word. Each call to `getchar` returns one integer, which
either represents:
- A single character - in the case of MIPS1 a `char` is 8-bits;
- Or the special EOF symbol, which we have defined to be `-1`
We need these two cases, because any 8-bit value could legally be read from `stdin`,
so we need something beyond 8-bits that will not be the same as any 8-bit value.

When performing the load to the getc address, this is equivalent to
one call to `getchar`, so we should get an integer that can represent either
a character or EOF. This makes `lw` the most natural version, as there are
257 values that it might load:
- 0x00000000 to 0x000000FF : Valid characters
- 0xFFFFFFFFF : EOF

This would then turn directly into the standard getchar paradigm:
```
int x=getchar();
if(x==-1){
    return  ...;
}
char c=(char)x;
```
which for the simulator becomes:
```
int x= *(int *)ADDR_GETC;
if(x==-1){
    return  ...;
}
char c=(char)x;
```

For `lh` we could still make it work, as -1 is still distinct from all the
characters, but there is a lack of clarity on which address it should
read from. The best guess is:
```
int16_t x= *(int16_t *)(ADDR_GETC+2);
```
but a possible alternative is:
```
int16_t x= *(int16_t *)(ADDR_GETC);
```

For `lb` things become a bit broken, as there is no way of distuinguishing
between EOF and a character. it is equivalent to:
```
char c=getchar();
if(c==-1){
   ... ;    // <- Did we get character (0xFF) or EOF (-1) ?
}
```
You'd also need to decide whether it maps to:
```
char x= *(char *)(ADDR_GETC+3);
```
or
```
char x= *(char *)(ADDR_GETC);
```

So given the spec as-is, the only well-defined operation becomes an aligned `lw`, `lwl`, or
`lwr` to the full 4-byte range, which returns one character for each read. Everything else
becomes implementation defined.

-

With regards to pressing a key, that would be the behaviour if stdin is connected to
the keyboard, e.g. with:
```
bin/mips_simulator my_binary
```
However, input could be coming from a file using:
```
cat wibble.input | bin/mips_simulator
```
or equivalently:
```
<wibble.input  bin/mips_simulator
```
It could even be coming from something like a network:
```
 echo "HELLO" | nc google.com 80 | bin/mips_simulator
```

**Comment by m8pple** [comment]
This was a good discussion, as it probed some interesting implementation
defined behaviour, and some under-specified parts of the spec. It certainly
made me think more carefully about an unanticipated corner-case of the spec.

Part of the reason I left it open was to see if anyone would propose a *definitive*
behaviour, i.e. refining the spec and trying to get one specific kind of behaviour
defined as the standard. It's not a problem that no-one did that, as we still have
a core of well-defined behaviour for aligned words, but it's always something
worth bearing in mind - if you are first to discover the corner case, then you
have a good opportunity to try to convince others that your interpretation
is correct. It doesn't always work, but is often worth a try.

So the earlier you realise there is an edge-case, the more opportunity you
have to distort reality to match your viewpoint. Usually the spec is actually
a contract with a client or project partners, and small changes to the spec
can have a huge impact on who bears the cost of complying with the spec.

**Comment by jjd06** [comment]
Archiving for 2018-19.
