### ISSUE TITLE
Testbench CSV Output Location

### ISSUE THREAD

**Issue by mahudu97** [m8pple/arch2-2018-cw#24]
Where should the testbench's CSV file be output to? 

In the spec, there is
"Any files **considered to be output** of the Testbench (for example per-test logfiles) should be **created in test/output**. However, there is **no requirement that output is created in either directory**."

So should the CSV file be written to 'test/output' or another location?

**Comment by m8pple** [comment]
The test-bench CSV output should be written to `stdout`. So if you run the test-bench
in the terminal, you should see the actual comma-separated output appear in the
terminal itself as the output of the command.

In order to capture the output of the testbench, a user can use redirection. So
for example, in order to write it to a file called `wibble.csv`, we would do:
```
bin/mips_testbench   ../other-simulator/bin/mips_simulator > wibble.csv
```

The files produced in `test/output` represent any other information produced
as a side-effect of running the test-bench. For example, it might contain the
exit code of each test-case, or the results from `stderr` for each test-case run.
This might be useful for anyone wanting to diagnose why a particular test
failed, but there is no requirement that anything at all is produced.
