### ISSUE TITLE
Simulator exit

### ISSUE THREAD

**Issue by mahudu97** [m8pple/arch2-2018-cw#25]
on exceptions and errors, the specification states to send -10, -11, -12, -20 or -21 to std::exit. To my understanding, echo $? will interpret the exit code as an unsigned 8-bit value, meaning echo $? can't differentiate between 5 potential values of the LSB of register 2 and the above codes.

Is this by design or am I reading the exit code using the wrong tool (echo $?)

**Comment by m8pple** [comment]
This is by design _and_ you are using the right tool.

It's more of an unhappy accommodation, because as you say,
[`exit` interprets it as an 8-bit value](http://man7.org/linux/man-pages/man3/exit.3.html):

> The exit() function causes normal process termination and the value
> of status & 0377 is returned to the parent (see wait(2)).

So we have an unfortunate aliasing problem, where negative exit codes look the
same as positive codes. So in your test-case design you should try to produce
valid results that _don't_ alias with negative results. For example, if small negative
numbers alias with exception codes, you could design your test-cases to return
small positive numbers.

You also have a side-channel of the `putc` address, which allows a test-case to
output arbitrary amounts of information - in some cases it is useful, but in most
it is not needed.
