### ISSUE TITLE
Where exactly is the hash

### ISSUE THREAD

**Issue by edpickup** [m8pple/arch2-2018-cw#29]
So I'm being dumb and tired, where exactly is the hash we're meant to submit located. Sorry, not getting a clear result from googling.

**Comment by m8pple** [comment]
You can either:
- Get it from the command line
- Get it from github

To get it from the command-line, you can do:
```
git log -1
```
For example, on a repository of mine, I get:
```
$ git log -1
commit c8c68da4e08796938998f8a029660935ed6eecc3 (HEAD -> master, origin/master)
Author: David Thomas <dt10@imperial.ac.uk>
Date:   Mon Dec 4 02:17:21 2017 +0000
```
That code `c8c68da4e08796938998f8a029660935ed6eecc3` is the commit hash.

You can also get it from github, by going to the repository page and:
- Clicking on the code at the top right of the files to get the last commit (figure A)
- Copying out the long 40 digit hex-code representing the hash.

I would strongly suggest doing both, and making sure that they match.

I would also *strongly* suggest that you clone your repository to a fresh
copy, then try building and running your simulator and test-bench there.
It is often the case that the build works correctly on one machine, but
only because certain files happen to exist there. Doing a fresh clone will
tell you if you forgot to add anything.


A:
![image](https://user-images.githubusercontent.com/3024705/33771668-bfa992ce-dc29-11e7-85a4-7d68a9ff91f0.png)

B:
![image](https://user-images.githubusercontent.com/3024705/33771724-01443090-dc2a-11e7-8b92-b5587f9edebe.png)

**Comment by edpickup** [comment]
Thank you
