### ISSUE TITLE
Getting a Warning when creating the .elf

### ISSUE THREAD

**Issue by VasiliosRallis** [m8pple/arch2-2018-cw#3]
When I try to create the .bin file of a test.cpp that I wrote, I get the following warning: 

mips-linux-gnu-g++ -W -Wall -O3 -fno-builtin -std=c++11 -nostdlib -Wl,-melf32btsmip -march=mips1 -nostartfiles -mno-check-zero-division -Wl,--gpsize=0 -static -Wl,-Bstatic -Wl,--build-id=none -T src/linker.ld testbench/test.mips.o -o testbench/test.mips.elf
/usr/lib/gcc-cross/mips-linux-gnu/5/../../../../mips-linux-gnu/bin/ld: warning: cannot find entry symbol entry; defaulting to 0000000001000000

It's just a warning so the .bin file is still created when I run the make command. But I don't understand what the warning means and how it affects the .elf that is created.

**Comment by m8pple** [comment]
Ah, good point - I think I mentally glossed over that error.

Every .elf file represents a complete binary, which can be loaded by the operating
system. Once the operating system has loaded the executable (much like your
Simulator has to load the Binary), it needs to know where to start execution.
Usually you would think of that as `main`, but actually under the hood there is
usually another default entry point called `start`, which is provided by the C
run-time library. So what actually happens when you run a program is:
1 - OS loads code and data into process address space
2 - Code at `start` begins executing, which is actually the C or C++ run-time library
3 - The C/C++ run-time library initialises a bunch of stuff, e.g. `stdin`, `std::cin`, `malloc`.
4 - The C/C++ run-time library calls `main`, and your code starts executing.

I wanted to make sure that the linker wasn't bringing in any of the standard libraries,
so was trying to control the entry point to be something else.

You can get rid of the error by one of:
1 - Renaming your test function to `entry`.
2 - Deleting the `ENTRY` section in the linker config file, and call your test function `start`.
3 - Change the `ENTRY` section to have the same name as your test function
4 - Specifying the `-e SYMBOL` override on the compilation command line (not recommended).
See the GNU linker docs for the [order of precedence](https://sourceware.org/binutils/docs/ld/Entry-Point.html#Entry-Point).

Or, as you say, it can be left alone, though I agree it is kind of annoying. The key thing
is to look at the symbols listed by `objdump -d`, and check that the instructions that
you want start at 0x1000000. Once you want multiple functions, then you need to be
careful that the function you want to be the entry point is the one at address 0x1000000.

One complication you may see if you play around is with [C++ name mangling](https://en.wikipedia.org/wiki/Name_mangling#C.2B.2B). If you put a function like:
```
int f()
{ return 10; }
```
in a file called `f.c`, then if you use `objdump` you'll see a symbol called `_f`. However,
if you put it in a file called `f.cpp`, then you'll see something which contains `f`, but also
has other random characters.

To force a function to have C linkage (rather than C++), you can change it to:
extern "C" int f()
{ return 10; }
```
Then it will appear as `_f` in the symbol table regardless of whether it is compiled
as C or C++.
