### ISSUE TITLE
Binary termination

### ISSUE THREAD

**Issue by olly-larkin** [m8pple/arch2-2018-cw#34]
Just needed some clarification on the termination of the binary program...  

Does the simulator terminate execution when it hits a 0 instruction (noop) or does there need to be an instruction in the mips binary that jumps to 0x0 at the end, for example "jr $zero"?

**Comment by jjd06** [comment]
As per the [spec](https://github.com/m8pple/arch2-2018-cw), your simulator should ordinarily terminate when the 'instruction' at address 0x0 is 'executed.' 0x0 is a valid MIPS instruction.

**Comment by olly-larkin** [comment]
But does it specifically have to execute the instruction with PC = 0, or does it need to execute an instruction the same as the one stored at address 0 (0x0 = SLL) before exiting?

**Comment by jjd06** [comment]
There should be no instruction (or data) at 0x0, hence why I quoted 'instruction' above. 0x0 is not specified to be part of the instruction (or data) memory. This address should be used only to indicate desired termination.

Since 0x0 is a valid instruction, it should be executed as such (_i.e._ have the effects defined by the ISA).
