### ISSUE TITLE
Inquiry on the loading of binaries

### ISSUE THREAD

**Issue by ghost** [m8pple/arch2-2018-cw#5]
When loading the binaries in our simulator, should we assume that the file name of the binary is entered as arguments for the program (argc, argv) or should the file name be sent through std::cin after the program is started?

**Comment by m8pple** [comment]
It must be passed as arguments (so argc+argc), due to this:

> Binary : the Binary location is passed as a command-line parameter, and
> should be the path of a binary file containing MIPS-1 big-endian instructions.

In the example given:
```
bin/mips_simulator x.bin
```
the parameter `x.bin` is the path of a file and will be available within the Simulator
as `argv[1]`, which you could then open with [`fopen`](http://www.cplusplus.com/reference/cstdio/fopen/), [`std::ifstream`](http://www.cplusplus.com/reference/fstream/ifstream/ifstream/),
or [`open`](https://linux.die.net/man/3/open).

It's up to the caller to make sure that the path is either absolute, or is
relative to the current working directory (as the Simulator has no other
way to work out what the relative path might be relative to).

When using the C or C++ library approaches (`fopen` and `std::ifstream`) some
caution is needed on [certain platforms](https://www.microsoft.com/en-gb/windows/)
to deal with binary versus text files, so be careful to specify that you want to
open the file in binary mode. (It is good practise to supply the binary flag even
if you are only targeting platforms that don't do newline translation).
