### ISSUE TITLE
Weird problem when trying to create a j instruction from assembly

### ISSUE THREAD

**Issue by wmvndrscht** [m8pple/arch2-2018-cw#7]
When trying to create a binary which includes a j instruction (jumping to a literal) I seem to get a b instruction (which is not equivalent). However, when creating binary from a j instruction (jumping to a symbol), there is an equivalent branch instruction created. As shown below.

I use your setup (makefile, linker etc), and use objdump to view resulting elf file. I create the instructions from mips assembly .s -> .mips.elf

![jtype](https://user-images.githubusercontent.com/22416707/32636223-b87c90bc-c5ab-11e7-96df-c3692b20cb31.jpg)\

![jtype2](https://user-images.githubusercontent.com/22416707/32636265-ed477208-c5ab-11e7-8dd6-c40172a17c94.jpg)

My main aim is just to try to get a nice j instruction binary but then stumbled upon what seems more of an obscure problem......

**Comment by m8pple** [comment]
I think this is todo with relative branches rather than absolute in the linker stage.
So there is a painful if convoluted logic to what it is trying to do - it wants to help, really!

It's useful to look at the immediate branch being encoded in the `b` instruction
(which is actually a `beq r0, r0, imm`, that the assembler is pretending is a `b`).

In the first case it is trying to branch by +1, so given the instruction is
at `0xc`, we end up at `0xc + 0x4 + 0x4` = `0x14` (the extra 0x4 is for
the branch delay slot (or [PC vs nPC](http://www.mrc.uidaho.edu/mrc/people/jff/digital/MIPSir.html))). (But why isn't it branching to `0x10`... :) )

-

I tried to replicate what you're doing by creating a file called `wibble.s`:
```
.set noreorder
.set noat
hello_there:
addu $4, $0, $0
addu $1, $2, $3
addu $4, $2, $3
j 0x4
addu $5, $2, $3
addu $5, $2, $3
addu $5, $2, $3
addu $5, $2, $3
```

I want to be able to create `wibble.mips.o` out of `wibble.s`, in the same way that
I could create it from `wibble.c`, so I added this rule to the makefile:
```
# Compile a s file into a MIPS object file
%.mips.o : %.s
    $(MIPS_CC) $(MIPS_CPPFLAGS) -c $< -o $@
```
(Anyone trying to copy and paste: the space before the rule _*must*_ be a tab, not spaces, otherwise
`make` won't accept it).

I then try to make it:
```
ubuntu@ubuntu-xenial:/vagrant$ make wibble.mips.elf -B
make: Warning: File 'wibble.s' has modification time 0.93 s in the future
mips-linux-gnu-gcc -W -Wall -O3 -fno-builtin -c wibble.s -o wibble.mips.o
mips-linux-gnu-gcc -W -Wall -O3 -fno-builtin -nostdlib -Wl,-melf32btsmip -march=mips1 -nostartfiles -mno-check-zero-division -Wl,--gpsize=0 -static -Wl,-Bstatic -Wl,--build-id=none -T src/linker.ld wibble.mips.o -o wibble.mips.elf
/usr/lib/gcc-cross/mips-linux-gnu/5/../../../../mips-linux-gnu/bin/ld: warning: cannot find entry symbol entry; defaulting to 0000000001000000
rm wibble.mips.o
```

Disassembling I get:
```
ubuntu@ubuntu-xenial:/vagrant$ mips-linux-gnu-objdump wibble.mips.elf -d

wibble.mips.elf:     file format elf32-tradbigmips


Disassembly of section .text:

01000000 <hello_there>:
 1000000:       00002021        move    a0,zero
 1000004:       00430821        addu    at,v0,v1
 1000008:       00432021        addu    a0,v0,v1
 100000c:       1000fffc        b       1000000 <hello_there>
 1000010:       00432821        addu    a1,v0,v1
 1000014:       00432821        addu    a1,v0,v1
 1000018:       00432821        addu    a1,v0,v1
 100001c:       00432821        addu    a1,v0,v1
```

So we find:
- The instructions are in the right place (0x1000000)
- Even though we have a relative jump, it is jumping to the right place
  _relative to the original symbol_. However the symbol has been relocated.
- It is definitely refusing to emit a `j` instruction...

Part of the joy of working at a low level is that you can generally tell the
tools to just ignore their idea of reality and just trust you. So if you
want to jump to 0x4 (I assume it is more experimentation, than what
you want to do in your Simulator), we can choose to emit the binary
instruction in the middle of some assembly:
```
.set noat
.set noreorder

hello_there:
addu $4, $0, $0
addu $1, $2, $3
addu $4, $2, $3
.word 0x08000001
addu $5, $2, $3
addu $5, $2, $3
addu $5, $2, $3
addu $5, $2, $3
```

After compiler and looking in objdump I get:
```
ubuntu@ubuntu-xenial:/vagrant$ make wibble.mips.elf -B
mips-linux-gnu-gcc -W -Wall -O3 -fno-builtin -c wibble.s -o wibble.mips.o
mips-linux-gnu-gcc -W -Wall -O3 -fno-builtin -nostdlib -Wl,-melf32btsmip -march=mips1 -nostartfiles -mno-check-zero-division -Wl,--gpsize=0 -static -Wl,-Bstatic -Wl,--build-id=none -T src/linker.ld wibble.mips.o -o wibble.mips.elf
/usr/lib/gcc-cross/mips-linux-gnu/5/../../../../mips-linux-gnu/bin/ld: warning: cannot find entry symbol entry; defaulting to 0000000001000000
rm wibble.mips.o
ubuntu@ubuntu-xenial:/vagrant$ mips-linux-gnu-objdump wibble.mips.elf -d

wibble.mips.elf:     file format elf32-tradbigmips


Disassembly of section .text:

01000000 <hello_there>:
 1000000:       00002021        move    a0,zero
 1000004:       00430821        addu    at,v0,v1
 1000008:       00432021        addu    a0,v0,v1
 100000c:       08000001        j       4 <hello_there-0xfffffc>
 1000010:       00432821        addu    a1,v0,v1
 1000014:       00432821        addu    a1,v0,v1
 1000018:       00432821        addu    a1,v0,v1
 100001c:       00432821        addu    a1,v0,v1
```
Notice that the assembler is trying to indicate where it is now jumping by working
out a negative relative address that can't be encoded with an immediate branch.

**Comment by VasiliosRallis** [comment]
How did you manage to get the branch to the right location?
When I compile:

```
.set noreorder
.set noat
hello_there:
addu $4, $0, $0
addu $1, $2, $3
addu $4, $2, $3
j 0x4
addu $5, $2, $3
addu $5, $2, $3
addu $5, $2, $3
addu $5, $2, $3
```
With the following command:

```
make test.mips.elf
mips-linux-gnu-gcc -W -Wall -O3 -fno-builtin -c test.s -o test.mips.o
mips-linux-gnu-gcc -W -Wall -O3 -fno-builtin -nostdlib -Wl,-melf32btsmip -march=mips1 -nostartfiles -mno-check-zero-division -Wl,--gpsize=0 -static -Wl,-Bstatic -Wl,--build-id=none -T src/linker.ld test.mips.o -o test.mips.elf
/usr/lib/gcc-cross/mips-linux-gnu/5/../../../../mips-linux-gnu/bin/ld: warning: cannot find entry symbol entry; defaulting to 0000000010000000
rm test.mips.o
```

I get exactly what Wim got:

```
vasilios@laptop:~/Documents/CPP/MipsPro$`` mips-linux-gnu-objdump test.mips.elf -d 
test.mips.elf:     file format elf32-tradbigmips


Disassembly of section .text:

10000000 <hello_there>:
10000000:	00002021 	move	a0,zero
10000004:	00430821 	addu	at,v0,v1
10000008:	00432021 	addu	a0,v0,v1
1000000c:	10000001 	b	10000014 <hello_there+0x14>
10000010:	00432821 	addu	a1,v0,v1
10000014:	00432821 	addu	a1,v0,v1
10000018:	00432821 	addu	a1,v0,v1
1000001c:	00432821 	addu	a1,v0,v1
```
As you can see, the branch isn't branching to the correct address.

**Comment by m8pple** [comment]
It's possible I pasted the wrong input in, as I get the same as you for the first version.

Ah, I think I didn't use exactly the same version - I must have edited before compiling. Try:
```
.set noreorder
.set noat
hello_there:
addu $4, $0, $0
addu $1, $2, $3
addu $4, $2, $3
j hello_there
addu $5, $2, $3
addu $5, $2, $3
addu $5, $2, $3
addu $5, $2, $3
```
and you'll get the output I listed:
```
10000000 <hello_there>:
10000000:       00002021        move    a0,zero
10000004:       00430821        addu    at,v0,v1
10000008:       00432021        addu    a0,v0,v1
1000000c:       1000fffc        b       10000000 <hello_there>
10000010:       00432821        addu    a1,v0,v1
10000014:       00432821        addu    a1,v0,v1
10000018:       00432821        addu    a1,v0,v1
1000001c:       00432821        addu    a1,v0,v1
```

You'll also get the same output for:
```
.set noreorder
.set noat
hello_there:
addu $4, $0, $0
addu $1, $2, $3
addu $4, $2, $3
j -0x10
addu $5, $2, $3
addu $5, $2, $3
addu $5, $2, $3
addu $5, $2, $3
```
(notice the assembler treating the negative jump as PC-relative).
